### ISSUE TITLE
Project has two names

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/UM2N#21]
The repository is called UM2N but the codebase is called WarpMesh. We should pick one name for simplicity and consistency.

**Comment by jwallwork23** [comment]
Majority vote for UM2N so we should change the `warpmesh/` subdirectory to `um2n` or `UM2N`. I don't have a strong preference which. Do you, @erizmr @chunyang-w?

**Comment by erizmr** [comment]
> Majority vote for UM2N so we should change the `warpmesh/` subdirectory to `um2n` or `UM2N`. I don't have a strong preference which. Do you, @erizmr @chunyang-w?

I don't either.
