### ISSUE TITLE
modify the introduction in about

### ISSUE THREAD

**Issue by erizmr** [mesh-adaptation/UM2N#28]
<img width="254" alt="1728604624309" src="https://github.com/user-attachments/assets/67bd1ace-631a-4b38-989e-68586ef37b98">

May I propose to modify the "UM2N code" here to "[NeurIPS 2024 Spotlight] Towards Universal Mesh Movement Networks"? It seems that I don't have the permissions to modify this.

**Comment by jwallwork23** [comment]
I've now made the requested update. I added https://erizmr.github.io/UM2N as the webpage, hopefully that's fine by you @erizmr?

**Comment by erizmr** [comment]
Many thanks Joe! @jwallwork23
