### ISSUE TITLE
Fix import

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/UM2N#57]
While looking at https://github.com/mesh-adaptation/mesh-adaptation-docs/pull/59, ~~I realised that the `test_import.py` test is not actually doing what it's meant to do.~~

Edit: I opened a PR which I thought fixes it, but then realised the actual issue... When you do `python3 -m pytest tests/test_import.py` from `firedrake/src/UM2N`, the test passes (as in the CI test suite). But it fails if you do `python3 -m pytest test_import.py` from `firedrake/src/UM2N/tests`. The former also fails if you do `pytest tests/test_import.py`.

So I guess python path might not be set correctly during installation?

**Comment by jwallwork23** [comment]
It seems to be okay in https://github.com/mesh-adaptation/UM2N/pull/59?

**Comment by ddundo** [comment]
> It seems to be okay in #59?

Well that uninstalls and then installs UM2N again. So maybe that fixes it, yeah. But could you please try it in the docker container as it is and see if you get the same error?

**Comment by jwallwork23** [comment]
> Well that uninstalls and then installs UM2N again. So maybe that fixes it, yeah. But could you please try it in the docker container as it is and see if you get the same error?

Sorry, it was a long day. I started digging into this, will get back to it later in the week. I think there's an issue with dependencies.

**Comment by ddundo** [comment]
> Sorry, it was a long day. I started digging into this, will get back to it later in the week. I think there's an issue with dependencies.

No worries, no rush at all from my side :)
